openapi: 3.0.0
info:
  title: Cleaner API
  description: API para limpiar datos masivamente
  version: 1.0.0

paths:
  /api/cleaner/exam-attempts:
    delete:
      tags:
        - Cleaner
      summary: Borrar todos los intentos de examen
      description: Elimina TODOS los intentos de examen de la base de datos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Intentos eliminados exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "TODOS los intentos de examen han sido eliminados exitosamente"
                  data:
                    type: object
                    properties:
                      deletedCount:
                        type: number
                        example: 25
                      totalFound:
                        type: number
                        example: 25
                      message:
                        type: string
                        example: "Se eliminaron 25 intentos de examen de un total de 25"
        '401':
          description: Usuario no autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Usuario no autenticado"
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Error al eliminar los intentos de examen"

  /api/cleaner/exams:
    delete:
      tags:
        - Cleaner
      summary: Borrar todos los exámenes
      description: Elimina TODOS los exámenes y sus intentos asociados de la base de datos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Exámenes eliminados exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "TODOS los exámenes han sido eliminados exitosamente"
                  data:
                    type: object
                    properties:
                      deletedExams:
                        type: number
                        example: 10
                      deletedAttempts:
                        type: number
                        example: 50
                      totalExamsFound:
                        type: number
                        example: 10
                      totalAttemptsFound:
                        type: number
                        example: 50
                      message:
                        type: string
                        example: "Se eliminaron 10 exámenes y 50 intentos asociados"
        '401':
          description: Usuario no autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Usuario no autenticado"
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Error al eliminar los exámenes"

  /api/cleaner/questions:
    delete:
      tags:
        - Cleaner
      summary: Borrar todas las preguntas
      description: Elimina TODAS las preguntas de la base de datos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Preguntas eliminadas exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "TODAS las preguntas han sido eliminadas exitosamente"
                  data:
                    type: object
                    properties:
                      deletedCount:
                        type: number
                        example: 100
                      totalQuestionsBefore:
                        type: number
                        example: 100
                      message:
                        type: string
                        example: "Se eliminaron 100 preguntas de un total de 100"
        '401':
          description: Usuario no autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Usuario no autenticado"
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Error al eliminar las preguntas"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 