openapi: 3.0.0
info:
  title: Labs API
  version: 2.0.0
  description: API for development, maintenance, and administrative operations
paths:
  # ===== USER MANAGEMENT ROUTES =====
  /api/labs/users/create-admin:
    post:
      summary: Create admin user for development
      tags:
        - Labs
      description: Creates a new admin user for development and testing purposes. This endpoint is typically used in development environments to seed the database with an admin user.
      security:
        - BearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Admin username (defaults to env USER_NOVA)
                email:
                  type: string
                  description: Admin email (defaults to admin@example.com)
                password:
                  type: string
                  description: Admin password (defaults to env PASSWORD_NOVA)
                firstName:
                  type: string
                  description: Admin first name (defaults to System)
                lastName:
                  type: string
                  description: Admin last name (defaults to Administrator)
      responses:
        '200':
          description: Admin user created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Admin user created successfully"
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        description: Created admin user object
        '401':
          description: Unauthorized - Token not provided
        '403':
          description: Forbidden - Invalid token or insufficient permissions
        '500':
          description: Error creating admin user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Error creating admin user"

  # ===== BACKUP AND MAINTENANCE ROUTES =====
  /api/labs/backup/send-email:
    post:
      summary: Send backup by email
      tags:
        - Labs
      description: Generates a complete backup of all collections and sends it via email. This endpoint creates backup files for words, lectures, expressions, exams, and questions, then emails them to the configured recipient.
      security:
        - BearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                recipient:
                  type: string
                  description: Email recipient (defaults to env BACKUP_EMAIL_RECIPIENT)
                includeCollections:
                  type: array
                  items:
                    type: string
                    enum: [words, lectures, expressions, exams, questions, users]
                  description: Collections to include in backup (defaults to all)
      responses:
        '200':
          description: Backup sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Backup sent by email successfully"
                  data:
                    type: object
                    description: Backup result object
        '401':
          description: Unauthorized - Token not provided
        '403':
          description: Forbidden - Invalid token or insufficient permissions
        '500':
          description: Error sending backup
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Error sending backup by email"

tags:
  - name: Labs
    description: Development, maintenance, and administrative operations