openapi: 3.0.0
info:
  title: Labs API
  version: 2.0.0
  description: API for development, maintenance, and administrative operations
paths:
  # ===== USER MANAGEMENT ROUTES =====
  /api/labs/users/create-admin:
    post:
      summary: Create admin user for development
      tags:
        - Labs
      description: Creates a new admin user for development and testing purposes. This endpoint is typically used in development environments to seed the database with an admin user.
      security:
        - BearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Admin username (defaults to env USER_NOVA)
                email:
                  type: string
                  description: Admin email (defaults to admin@example.com)
                password:
                  type: string
                  description: Admin password (defaults to env PASSWORD_NOVA)
                firstName:
                  type: string
                  description: Admin first name (defaults to System)
                lastName:
                  type: string
                  description: Admin last name (defaults to Administrator)
      responses:
        '200':
          description: Admin user created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Admin user created successfully"
                  data:
                    type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/AdminUser'
        '401':
          description: Unauthorized - Token not provided
        '403':
          description: Forbidden - Invalid token or insufficient permissions
        '500':
          description: Error creating admin user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Error creating admin user"

  # ===== BACKUP AND MAINTENANCE ROUTES =====
  /api/labs/backup/send-email:
    post:
      summary: Send backup by email
      tags:
        - Labs
      description: Generates a complete backup of all collections and sends it via email. This endpoint creates backup files for words, lectures, expressions, exams, and questions, then emails them to the configured recipient.
      security:
        - BearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                recipient:
                  type: string
                  description: Email recipient (defaults to env BACKUP_EMAIL_RECIPIENT)
                includeCollections:
                  type: array
                  items:
                    type: string
                    enum: [words, lectures, expressions, exams, questions, users]
                  description: Collections to include in backup (defaults to all)
      responses:
        '200':
          description: Backup sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Backup sent by email successfully"
                  data:
                    $ref: '#/components/schemas/BackupResult'
        '401':
          description: Unauthorized - Token not provided
        '403':
          description: Forbidden - Invalid token or insufficient permissions
        '500':
          description: Error sending backup
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Error sending backup by email"

components:
  schemas:
    AdminUser:
      type: object
      properties:
        _id:
          type: string
          example: "507f1f77bcf86cd799439011"
        username:
          type: string
          example: "admin"
          description: Admin username
        email:
          type: string
          example: "admin@example.com"
          description: Admin email address
        role:
          type: string
          enum: [admin]
          example: "admin"
          description: User role
        firstName:
          type: string
          example: "System"
          description: Admin first name
        lastName:
          type: string
          example: "Administrator"
          description: Admin last name
        isActive:
          type: boolean
          example: true
          description: Whether the user is active
        createdAt:
          type: string
          format: date-time
          example: "2025-01-15T10:30:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-01-15T10:30:00.000Z"
      required:
        - username
        - email
        - role
        - firstName
        - lastName
        - isActive

    BackupResult:
      type: object
      properties:
        wordsCount:
          type: integer
          example: 150
          description: Number of words in backup
        lecturesCount:
          type: integer
          example: 25
          description: Number of lectures in backup
        expressionsCount:
          type: integer
          example: 75
          description: Number of expressions in backup
        examsCount:
          type: integer
          example: 10
          description: Number of exams in backup
        questionsCount:
          type: integer
          example: 50
          description: Number of questions in backup
        emailSent:
          type: boolean
          example: true
          description: Whether the email was sent successfully
        messageId:
          type: string
          example: "msg_123456789"
          description: Email message ID (if sent successfully)
        timestamp:
          type: string
          format: date-time
          example: "2025-01-15T10:30:00.000Z"
          description: Backup timestamp
        error:
          type: string
          example: null
          description: Error message (if any)
      required:
        - wordsCount
        - lecturesCount
        - expressionsCount
        - examsCount
        - questionsCount
        - emailSent
        - timestamp

    BackupCollection:
      type: object
      properties:
        name:
          type: string
          example: "words"
          description: Collection name
        count:
          type: integer
          example: 150
          description: Number of documents in collection
        filename:
          type: string
          example: "words-backup-2025-01-15T10-30-00-000Z.json"
          description: Backup filename
        size:
          type: string
          example: "2.5MB"
          description: File size
        status:
          type: string
          enum: [success, error, skipped]
          example: "success"
          description: Backup status

    BackupEmailConfig:
      type: object
      properties:
        recipient:
          type: string
          example: "admin@example.com"
          description: Email recipient
        subject:
          type: string
          example: "🔒 Backup Diario - LanguageAI [15/01/2025]"
          description: Email subject
        enabled:
          type: boolean
          example: true
          description: Whether email backup is enabled
        cronSchedule:
          type: string
          example: "0 30 23 * * *"
          description: Cron schedule for automatic backups
        timezone:
          type: string
          example: "America/New_York"
          description: Timezone for cron schedule

    BackupSchedulerStatus:
      type: object
      properties:
        isActive:
          type: boolean
          example: true
          description: Whether the backup scheduler is active
        lastRunTime:
          type: string
          format: date-time
          example: "2025-01-15T10:30:00.000Z"
          description: Last backup run time
        nextRunTime:
          type: string
          format: date-time
          example: "2025-01-16T10:30:00.000Z"
          description: Next scheduled backup time
        totalRuns:
          type: integer
          example: 30
          description: Total number of backup runs
        successfulRuns:
          type: integer
          example: 28
          description: Number of successful backup runs
        failedRuns:
          type: integer
          example: 2
          description: Number of failed backup runs
        schedule:
          type: string
          example: "0 30 23 * * *"
          description: Current cron schedule
        timezone:
          type: string
          example: "America/New_York"
          description: Scheduler timezone

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "An error occurred"
        error:
          type: string
          example: "Detailed error message"
        timestamp:
          type: string
          format: date-time
          example: "2025-01-15T10:30:00.000Z"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

tags:
  - name: Labs
    description: Development, maintenance, and administrative operations