openapi: 3.0.0
info:
  title: Statistics API
  version: 1.0.0
  description: API for comprehensive statistics and analytics

paths:
  /api/statistics:
    get:
      tags:
        - Statistics
      summary: Basic Statistics
      description: Get basic statistics for lectures and words by level
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Basic statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      lectures:
                        type: object
                        properties:
                          A1:
                            type: integer
                            description: Number of A1 level lectures
                          A2:
                            type: integer
                            description: Number of A2 level lectures
                          B1:
                            type: integer
                            description: Number of B1 level lectures
                          B2:
                            type: integer
                            description: Number of B2 level lectures
                          C1:
                            type: integer
                            description: Number of C1 level lectures
                          C2:
                            type: integer
                            description: Number of C2 level lectures
                          total:
                            type: integer
                            description: Total number of lectures
                      words:
                        type: object
                        properties:
                          easy:
                            type: integer
                            description: Number of easy level words
                          medium:
                            type: integer
                            description: Number of medium level words
                          hard:
                            type: integer
                            description: Number of hard level words
                          total:
                            type: integer
                            description: Total number of words
        '404':
          description: Error getting statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/statistics/dashboard:
    get:
      tags:
        - Statistics
      summary: Dashboard Statistics
      description: Get comprehensive dashboard statistics including overview, distribution, quality metrics, and engagement data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dashboard statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      overview:
                        type: object
                        properties:
                          totalContent:
                            type: object
                            properties:
                              lectures:
                                type: integer
                                description: Total number of lectures
                              words:
                                type: integer
                                description: Total number of words
                          contentQuality:
                            type: object
                            properties:
                              lecturesWithAudio:
                                type: integer
                                description: Number of lectures with audio
                              lecturesWithImages:
                                type: integer
                                description: Number of lectures with images
                              wordsWithExamples:
                                type: integer
                                description: Number of words with examples
                              wordsWithImages:
                                type: integer
                                description: Number of words with images
                              overallQualityScore:
                                type: integer
                                description: Overall quality score (0-100)
                          recentActivity:
                            type: object
                            properties:
                              recentLectures:
                                type: integer
                                description: Number of lectures created in last 30 days
                              recentWords:
                                type: integer
                                description: Number of words created in last 30 days
                      byLevel:
                        type: object
                        properties:
                          lectures:
                            type: object
                            properties:
                              A1:
                                type: integer
                              A2:
                                type: integer
                              B1:
                                type: integer
                              B2:
                                type: integer
                              C1:
                                type: integer
                              C2:
                                type: integer
                          words:
                            type: object
                            properties:
                              easy:
                                type: integer
                              medium:
                                type: integer
                              hard:
                                type: integer
                      byLanguage:
                        type: object
                        properties:
                          lectures:
                            type: object
                            additionalProperties:
                              type: integer
                            description: Distribution of lectures by language
                          words:
                            type: object
                            additionalProperties:
                              type: integer
                            description: Distribution of words by language
                      quality:
                        type: object
                        properties:
                          lecturesWithoutAudio:
                            type: integer
                            description: Number of lectures without audio
                          lecturesWithoutImages:
                            type: integer
                            description: Number of lectures without images
                          wordsWithoutExamples:
                            type: integer
                            description: Number of words without examples
                          wordsWithoutImages:
                            type: integer
                            description: Number of words without images
                          lectureQualityScore:
                            type: integer
                            description: Quality score for lectures (0-100)
                          wordQualityScore:
                            type: integer
                            description: Quality score for words (0-100)
                      engagement:
                        type: object
                        properties:
                          averageLectureTime:
                            type: number
                            description: Average reading time in minutes
                          averageWordSeen:
                            type: number
                            description: Average times words have been seen
        '500':
          description: Error getting dashboard statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/statistics/lectures:
    get:
      tags:
        - Statistics
      summary: Lecture Statistics
      description: Get detailed statistics for lectures including distribution, quality metrics, and engagement data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lecture statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      overview:
                        type: object
                        properties:
                          total:
                            type: integer
                            description: Total number of lectures
                          recent:
                            type: integer
                            description: Number of lectures created in last 30 days
                          qualityScore:
                            type: integer
                            description: Quality score (0-100)
                      distribution:
                        type: object
                        properties:
                          byLevel:
                            type: object
                            properties:
                              A1:
                                type: integer
                              A2:
                                type: integer
                              B1:
                                type: integer
                              B2:
                                type: integer
                              C1:
                                type: integer
                              C2:
                                type: integer
                          byLanguage:
                            type: object
                            additionalProperties:
                              type: integer
                            description: Distribution of lectures by language
                      quality:
                        type: object
                        properties:
                          withAudio:
                            type: integer
                            description: Number of lectures with audio
                          withImages:
                            type: integer
                            description: Number of lectures with images
                          withoutAudio:
                            type: integer
                            description: Number of lectures without audio
                          withoutImages:
                            type: integer
                            description: Number of lectures without images
                      metrics:
                        type: object
                        properties:
                          averageTimeByLevel:
                            type: object
                            additionalProperties:
                              type: integer
                            description: Average reading time by level (in minutes)
                          averageTimeOverall:
                            type: integer
                            description: Overall average reading time (in minutes)
        '500':
          description: Error getting lecture statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/statistics/words:
    get:
      tags:
        - Statistics
      summary: Word Statistics
      description: Get detailed statistics for words including distribution, quality metrics, and engagement data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Word statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      overview:
                        type: object
                        properties:
                          total:
                            type: integer
                            description: Total number of words
                          recent:
                            type: integer
                            description: Number of words created in last 30 days
                          qualityScore:
                            type: integer
                            description: Quality score (0-100)
                      distribution:
                        type: object
                        properties:
                          byLevel:
                            type: object
                            properties:
                              easy:
                                type: integer
                              medium:
                                type: integer
                              hard:
                                type: integer
                          byLanguage:
                            type: object
                            additionalProperties:
                              type: integer
                            description: Distribution of words by language
                      quality:
                        type: object
                        properties:
                          withExamples:
                            type: integer
                            description: Number of words with examples
                          withImages:
                            type: integer
                            description: Number of words with images
                          withoutExamples:
                            type: integer
                            description: Number of words without examples
                          withoutImages:
                            type: integer
                            description: Number of words without images
                      metrics:
                        type: object
                        properties:
                          averageSeenByLevel:
                            type: object
                            additionalProperties:
                              type: integer
                            description: Average times seen by level
                          averageSeenOverall:
                            type: integer
                            description: Overall average times seen
        '500':
          description: Error getting word statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Error message"
        error:
          type: object
          description: Error details