openapi: 3.0.0
info:
  title: User API
  version: 2.0.0
  description: API for user management, authentication, and administrative operations
paths:
  # ===== AUTHENTICATION ROUTES =====
  /api/auth/login:
    post:
      summary: User login
      tags:
        - Authentication
      description: Authenticate user and return JWT tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  description: Username or email for authentication
                  example: "novask88"
                password:
                  description: User password
                  example: "sashateamomucho"
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Login successful"
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                        description: JWT access token
                      refreshToken:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                        description: JWT refresh token
                      user:
                        type: object
                        description: User information
        '400':
          description: Username and password are required
        '401':
          description: Invalid credentials
        '500':
          description: Authentication failed

  /api/auth/refresh:
    post:
      summary: Refresh access token
      tags:
        - Authentication
      description: Refresh JWT access token using refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  description: JWT refresh token
              required:
                - refreshToken
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Token refreshed successfully"
                  data:
                    type: object
                    properties:
                      accessToken:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                        description: New JWT access token
                      refreshToken:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                        description: New JWT refresh token
                      user:
                        type: object
                        description: User information
        '400':
          description: Refresh token is required
        '401':
          description: Invalid refresh token
        '500':
          description: Failed to refresh token

  # ===== USER MANAGEMENT ROUTES =====
  /api/users:
    get:
      summary: Get all users with filters
      tags:
        - Users
      description: Retrieve users with comprehensive filtering and pagination options
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
            minimum: 1
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
            minimum: 1
          description: Number of users per page
        - in: query
          name: username
          schema:
            type: string
          description: Filter by username (partial match)
        - in: query
          name: email
          schema:
            type: string
          description: Filter by email (partial match)
        - in: query
          name: role
          schema:
            type: string
            enum: [admin, teacher, student]
          description: Filter by user role
        - in: query
          name: language
          schema:
            type: string
            enum: [es, en, fr, de, it, pt]
          description: Filter by language preference
        - in: query
          name: isActive
          schema:
            type: boolean
          description: Filter by active status
        - in: query
          name: phone
          schema:
            type: string
          description: Filter by phone number (partial match)
        - in: query
          name: address
          schema:
            type: string
          description: Filter by address (partial match)
        - in: query
          name: createdAfter
          schema:
            type: string
            format: date-time
          description: Filter users created after this date
        - in: query
          name: createdBefore
          schema:
            type: string
            format: date-time
          description: Filter users created before this date
        - in: query
          name: updatedAfter
          schema:
            type: string
            format: date-time
          description: Filter users updated after this date
        - in: query
          name: updatedBefore
          schema:
            type: string
            format: date-time
          description: Filter users updated before this date
        - in: query
          name: sortBy
          schema:
            type: string
            enum: [createdAt, updatedAt, username, email, role, language, lastLogin]
            default: createdAt
          description: Field to sort by
        - in: query
          name: sortOrder
          schema:
            type: string
            enum: [asc, desc]
            default: desc
          description: Sort order
      responses:
        '200':
          description: Users retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Users listed successfully"
                  data:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          description: User object
                      total:
                        type: integer
                        example: 100
                      page:
                        type: integer
                        example: 1
                      pages:
                        type: integer
                        example: 10
        '401':
          description: Unauthorized - Token not provided
        '403':
          description: Forbidden - Invalid token
        '500':
          description: Internal server error

    post:
      summary: Create a new user
      tags:
        - Users
      description: Create a new user account
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Unique username
                email:
                  type: string
                  description: Unique email address
                password:
                  type: string
                  description: User password
                role:
                  type: string
                  enum: [admin, teacher, student]
                  description: User role
                firstName:
                  type: string
                  description: User first name
                lastName:
                  type: string
                  description: User last name
                address:
                  type: string
                  description: User address
                phone:
                  type: string
                  description: User phone number
              required:
                - username
                - email
                - password
                - role
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "User created successfully"
                  data:
                    type: object
                    description: Created user object
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Username already exists"
        '401':
          description: Unauthorized - Token not provided
        '403':
          description: Forbidden - Invalid token
        '500':
          description: Internal server error

  /api/users/{id}:
    get:
      summary: Get user by ID
      tags:
        - Users
      description: Retrieve a specific user by their ID
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: User ID
      responses:
        '200':
          description: User retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "User found"
                  data:
                    type: object
                    description: User object
        '401':
          description: Unauthorized - Token not provided
        '403':
          description: Forbidden - Invalid token
        '404':
          description: User not found
        '500':
          description: Internal server error

    put:
      summary: Update user
      tags:
        - Users
      description: Update an existing user account
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: User ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Updated username
                email:
                  type: string
                  description: Updated email address
                firstName:
                  type: string
                  description: Updated first name
                lastName:
                  type: string
                  description: Updated last name
                address:
                  type: string
                  description: Updated address
                phone:
                  type: string
                  description: Updated phone number
                isActive:
                  type: boolean
                  description: Updated active status
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "User updated successfully"
                  data:
                    type: object
                    description: Updated user object
        '400':
          description: Validation error
        '401':
          description: Unauthorized - Token not provided
        '403':
          description: Forbidden - Invalid token
        '404':
          description: User not found
        '500':
          description: Internal server error

    delete:
      summary: Delete user
      tags:
        - Users
      description: Delete a user account
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: User ID
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "User deleted successfully"
                  data:
                    type: object
                    description: Deleted user object
        '401':
          description: Unauthorized - Token not provided
        '403':
          description: Forbidden - Invalid token
        '404':
          description: User not found
        '500':
          description: Internal server error

  # ===== IMPORT/EXPORT ROUTES =====
  /api/users/export-file:
    get:
      summary: Export users to JSON file
      tags:
        - Users
      description: Downloads a JSON file containing all users in the database
      security:
        - BearerAuth: []
      responses:
        '200':
          description: JSON file with all users
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Exported 100 users successfully"
                  data:
                    type: object
                    properties:
                      totalUsers:
                        type: number
                        example: 100
                      exportDate:
                        type: string
                        format: date-time
                        example: "2025-01-15T10:30:00.000Z"
                      users:
                        type: array
                        items:
                          type: object
                          description: User object
        '401':
          description: Unauthorized - Token not provided
        '403':
          description: Forbidden - Invalid token
        '500':
          description: Internal server error

  /api/users/import-file:
    post:
      summary: Import users from JSON file
      tags:
        - Users
      description: Import users from a JSON file with various duplicate handling strategies
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: duplicateStrategy
          schema:
            type: string
            enum: [skip, overwrite, error, merge]
            default: skip
          description: Strategy to handle duplicate users
        - in: query
          name: validateOnly
          schema:
            type: boolean
            default: false
          description: If true, only validates the file without importing
        - in: query
          name: batchSize
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
          description: Number of users to process in each batch
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: JSON file containing users to import
      responses:
        '200':
          description: Import completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Import completed successfully"
                  data:
                    type: object
                    description: Import result object
        '400':
          description: Bad request - Invalid file format or parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Invalid JSON file format"
        '401':
          description: Unauthorized - Token not provided
        '403':
          description: Forbidden - Invalid token
        '500':
          description: Internal server error during import

tags:
  - name: Users
    description: User management and administrative operations
  - name: Authentication
    description: User authentication and token management